<a href="https://colab.research.google.com/github/Hemanthemani/Fuel_Consumption_CO2/blob/main/FuelConsumptionCO2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_csv('/content/FuelConsumptionCo2.csv')

In [ ]:
df1.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
df1.isnull().sum()

MODELYEAR                   0
MAKE                        0
MODEL                       0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELTYPE                    0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
dtype: int64

In [ ]:
x=df1.iloc[:,[4,5,8,9,10,11]]

In [ ]:
y=df1.iloc[:,-1]

In [ ]:
x

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG
0,2.0,4,9.9,6.7,8.5,33
1,2.4,4,11.2,7.7,9.6,29
2,1.5,4,6.0,5.8,5.9,48
3,3.5,6,12.7,9.1,11.1,25
4,3.5,6,12.1,8.7,10.6,27
...,...,...,...,...,...,...
1062,3.0,6,13.4,9.8,11.8,24
1063,3.2,6,13.2,9.5,11.5,25
1064,3.0,6,13.4,9.8,11.8,24
1065,3.2,6,12.9,9.3,11.3,25
1066,3.2,6,14.9,10.2,12.8,22

In [ ]:
from sklearn import datasets, linear_model, metrics
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3,
                                                    random_state=1)
reg = linear_model.LinearRegression()
reg.fit(X_train, y_train)
y_pred=reg.predict(X_test)
print(reg.intercept_)
print(reg.coef_)
print('MSE',metrics.mean_squared_error(y_test, y_pred))
print('R_squred_error',metrics.r2_score(y_test, y_pred))

264.9326714234362
[ 9.54929095  7.09198807 -8.76814262 -1.5669817  13.58411529 -4.06683162]
MSE 481.90122802122846
R_squred_error 0.8866215743986171

In [ ]:
df3 = pd.get_dummies(df1, columns = ['FUELTYPE'])

In [ ]:
df3.drop(['MODELYEAR','MAKE','VEHICLECLASS','TRANSMISSION','MODEL','FUELTYPE_Z'],axis=1,inplace=True)

In [ ]:
df3

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,FUELTYPE_D,FUELTYPE_E,FUELTYPE_X
0,2.0,4,9.9,6.7,8.5,33,196,0,0,0
1,2.4,4,11.2,7.7,9.6,29,221,0,0,0
2,1.5,4,6.0,5.8,5.9,48,136,0,0,0
3,3.5,6,12.7,9.1,11.1,25,255,0,0,0
4,3.5,6,12.1,8.7,10.6,27,244,0,0,0
...,...,...,...,...,...,...,...,...,...,...
1062,3.0,6,13.4,9.8,11.8,24,271,0,0,1
1063,3.2,6,13.2,9.5,11.5,25,264,0,0,1
1064,3.0,6,13.4,9.8,11.8,24,271,0,0,1
1065,3.2,6,12.9,9.3,11.3,25,260,0,0,1
1066,3.2,6,14.9,10.2,12.8,22,294,0,0,1

In [ ]:
Y=df3['CO2EMISSIONS'].values
X=df3.drop(['CO2EMISSIONS'],axis=1)

In [ ]:
from sklearn import datasets, linear_model, metrics
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,
                                                    random_state=1)
reg = linear_model.LinearRegression()
reg.fit(X_train, y_train)
y_pred=reg.predict(X_test)
print(reg.intercept_)
print(reg.coef_)
print('MSE',metrics.mean_squared_error(y_test, y_pred))
print('R_squred_error',metrics.r2_score(y_test, y_pred))

84.31167673644043
[   0.95306874    1.11908077   -4.300995     -4.32231266   26.44497931
   -1.42967269   32.66503237 -109.5313583     0.96952198]
MSE 32.70122533370336
R_squred_error 0.992306279320359

In [ ]:
import statsmodels.api as smf

In [ ]:
x_opt=X  
regressor_OLS=smf.OLS(endog = Y, exog=x_opt).fit()  
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.999
Model:                            OLS   Adj. R-squared (uncentered):              0.999
Method:                 Least Squares   F-statistic:                          1.843e+05
Date:                Mon, 11 Apr 2022   Prob (F-statistic):                        0.00
Time:                        16:40:49   Log-Likelihood:                         -3537.8
No. Observations:                1067   AIC:                                      7094.
Df Residuals:                    1058   BIC:                                      7138.
Df Model:                           9
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
ENGINESIZE                  -0.3658      0.459     -0.797      0.426      -1.267       0.535
CYLINDERS                    1.7522      0.350      5.010      0.000       1.066       2.438
FUELCONSUMPTION_CITY        -3.3386      3.943     -0.847      0.397     -11.075       4.398
FUELCONSUMPTION_HWY         -4.9563      3.251     -1.525      0.128     -11.335       1.422
FUELCONSUMPTION_COMB        29.7057      7.168      4.144      0.000      15.641      43.771
FUELCONSUMPTION_COMB_MPG     0.1280      0.023      5.597      0.000       0.083       0.173
FUELTYPE_D                  31.0694      1.363     22.792      0.000      28.395      33.744
FUELTYPE_E                -118.3864      1.070   -110.613      0.000    -120.486    -116.286
FUELTYPE_X                   1.0097      0.476      2.122      0.034       0.076       1.944
==============================================================================
Omnibus:                      288.192   Durbin-Watson:                   2.187
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            21023.516
Skew:                           0.093   Prob(JB):                         0.00
Kurtosis:                      24.745   Cond. No.                     1.46e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.46e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
x_opt.drop(['ENGINESIZE'],axis=1,inplace=True)
regressor_OLS=smf.OLS(endog = Y, exog=x_opt).fit()  
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.999
Model:                            OLS   Adj. R-squared (uncentered):              0.999
Method:                 Least Squares   F-statistic:                          2.074e+05
Date:                Mon, 11 Apr 2022   Prob (F-statistic):                        0.00
Time:                        16:40:56   Log-Likelihood:                         -3538.1
No. Observations:                1067   AIC:                                      7092.
Df Residuals:                    1059   BIC:                                      7132.
Df Model:                           8
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
CYLINDERS                    1.5435      0.232      6.661      0.000       1.089       1.998
FUELCONSUMPTION_CITY        -3.3545      3.942     -0.851      0.395     -11.089       4.380
FUELCONSUMPTION_HWY         -4.9906      3.250     -1.536      0.125     -11.367       1.386
FUELCONSUMPTION_COMB        29.7284      7.167      4.148      0.000      15.666      43.791
FUELCONSUMPTION_COMB_MPG     0.1386      0.019      7.448      0.000       0.102       0.175
FUELTYPE_D                  31.0266      1.362     22.782      0.000      28.354      33.699
FUELTYPE_E                -118.3037      1.065   -111.078      0.000    -120.394    -116.214
FUELTYPE_X                   0.9517      0.470      2.024      0.043       0.029       1.874
==============================================================================
Omnibus:                      288.115   Durbin-Watson:                   2.188
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            21091.520
Skew:                           0.085   Prob(JB):                         0.00
Kurtosis:                      24.780   Cond. No.                     1.45e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
x_opt.drop(['FUELCONSUMPTION_CITY'],axis=1,inplace=True)
regressor_OLS=smf.OLS(endog = Y, exog=x_opt).fit()  
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.999
Model:                            OLS   Adj. R-squared (uncentered):              0.999
Method:                 Least Squares   F-statistic:                          2.371e+05
Date:                Mon, 11 Apr 2022   Prob (F-statistic):                        0.00
Time:                        16:41:42   Log-Likelihood:                         -3538.5
No. Observations:                1067   AIC:                                      7091.
Df Residuals:                    1060   BIC:                                      7126.
Df Model:                           7
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
CYLINDERS                    1.5383      0.232      6.642      0.000       1.084       1.993
FUELCONSUMPTION_HWY         -2.2561      0.486     -4.646      0.000      -3.209      -1.303
FUELCONSUMPTION_COMB        23.6412      0.439     53.862      0.000      22.780      24.502
FUELCONSUMPTION_COMB_MPG     0.1390      0.019      7.471      0.000       0.102       0.175
FUELTYPE_D                  31.0891      1.360     22.864      0.000      28.421      33.757
FUELTYPE_E                -118.3019      1.065   -111.091      0.000    -120.391    -116.212
FUELTYPE_X                   0.9581      0.470      2.038      0.042       0.036       1.881
==============================================================================
Omnibus:                      289.007   Durbin-Watson:                   2.194
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            21420.110
Skew:                           0.086   Prob(JB):                         0.00
Kurtosis:                      24.949   Cond. No.                         208.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
x_opt.drop(['FUELTYPE_X'],axis=1,inplace=True)
regressor_OLS=smf.OLS(endog = Y, exog=x_opt).fit()  
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.999
Model:                            OLS   Adj. R-squared (uncentered):              0.999
Method:                 Least Squares   F-statistic:                          2.758e+05
Date:                Mon, 11 Apr 2022   Prob (F-statistic):                        0.00
Time:                        16:42:22   Log-Likelihood:                         -3540.6
No. Observations:                1067   AIC:                                      7093.
Df Residuals:                    1061   BIC:                                      7123.
Df Model:                           6
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
CYLINDERS                    1.4292      0.226      6.333      0.000       0.986       1.872
FUELCONSUMPTION_HWY         -2.1603      0.484     -4.463      0.000      -3.110      -1.211
FUELCONSUMPTION_COMB        23.6268      0.440     53.756      0.000      22.764      24.489
FUELCONSUMPTION_COMB_MPG     0.1550      0.017      9.178      0.000       0.122       0.188
FUELTYPE_D                  30.5537      1.336     22.868      0.000      27.932      33.175
FUELTYPE_E                -118.9722      1.014   -117.289      0.000    -120.963    -116.982
==============================================================================
Omnibus:                      288.806   Durbin-Watson:                   2.194
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            21564.605
Skew:                           0.064   Prob(JB):                         0.00
Kurtosis:                      25.024   Cond. No.                         205.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
from sklearn import datasets, linear_model, metrics
X_train, X_test, y_train, y_test = train_test_split(x_opt, Y, test_size=0.3,
                                                    random_state=1)
reg = linear_model.LinearRegression()
reg.fit(X_train, y_train)
y_pred=reg.predict(X_test)
print(reg.intercept_)
print(reg.coef_)
print('MSE',metrics.mean_squared_error(y_test, y_pred))
print('R_squred_error',metrics.r2_score(y_test, y_pred))

82.85310282589822
[   1.53692425   -0.70286841   18.74137648   -1.40880081   32.15856785
 -110.68693461]
MSE 32.65322986732619
R_squred_error 0.9923175713654865

In [ ]:
import statsmodels.api as sm
import pandas as pd


X = sm.add_constant(X)
model = sm.OLS(Y,x_opt).fit()

#display adjusted R-squared
print(model.rsquared_adj)

0.9993556216236854

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py:117: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)